### ISSUE TITLE
Feature Request: Can you echo Bing data to the console when --verbose is selected?

### ISSUE THREAD

**Issue by Trahloc** [GiusTex/EdgeGPT#1]
I'm trying to figure out what is being sent to Bing and what is my AI model hallucinating Bing results. 

![image](https://user-images.githubusercontent.com/1835014/235331598-4facec97-95b8-4380-8320-d4c2650df26c.png)

I would like see what is being sent to Bing vs what is the AI model's interpretation of Bing results. It would be helpful to have a console or log that shows the specific information that was sent to Bing and Bing's raw response. This would provide ground truth and help me understand if the conversation was successfully sent to Bing, even if "Show Bing Output" is not selected. Thank you for considering this feature.

**Comment by GiusTex** [comment]
I don't know how to make the code see if --verbose is on, but I can work around that by adding a button to the interface. Now I'm adding it, when you activate it you can choose what to print in the console (I too used to print in the console, I confirm that in fact it could be useful for others too)
