### ISSUE TITLE
Colab Compatible 

### ISSUE THREAD

**Issue by ImaBlank2** [GiusTex/EdgeGPT#10]
Currently works great using it locally but when i tried to use the extension in colab, it never search which kinda left me disappointed as to why it doesn't, is there a way to fix this issue and make it compatible through oobabooga in google colab?

**Comment by GiusTex** [comment]
I never tested it on colab, I'm testing it now to see if it could work

**Comment by GiusTex** [comment]
Uhm it works for me, what text-generation-webui colab are you using? If you are using [camenduru](https://github.com/camenduru/text-generation-webui-colab)'s one you need to change text-generation-webui>modules>text_generation.py with [oobabooga](https://github.com/oobabooga/text-generation-webui/blob/main/modules/text_generation.py)'s one

**Comment by GiusTex** [comment]
I don't know how to make it work in the text-generation-webui, sorry. When I test the file alone it works:
![image](https://github.com/GiusTex/EdgeGPT/assets/112352961/2f3fa1e5-3e02-42eb-a62a-d1d0665fa382)

Above I run this file [test_script.txt](https://github.com/GiusTex/EdgeGPT/files/11469963/test_script.txt), and EdgeGPT works (if you want to test it, rename txt to py). When the file [script.txt](https://github.com/GiusTex/EdgeGPT/files/11469974/script.txt) is instead inside the webui system (images below) the EdgeGPT part doesn't start, and I don't understand why. If you want to test it, rename txt to py, and upload script.py and the cookies in the EdgeGPT folder. This is an example colab webui made by camenduru and edited a bit by me: [pyg-7b-GPTQ-4bit-128g.txt](https://github.com/GiusTex/EdgeGPT/files/11469987/pyg-7b-GPTQ-4bit-128g.txt), to use it rename txt to ipynb, and use it on colab.

![image](https://github.com/GiusTex/EdgeGPT/assets/112352961/e940d8c5-c9d6-42e7-b5fb-e57d38877fcc)
![image](https://github.com/GiusTex/EdgeGPT/assets/112352961/35a8b0db-8b24-44e8-87fe-764466e267b1)

**Comment by GiusTex** [comment]
If you find a way to make EdgeGPT work on colab (using the files above or making your new ones) you can open again this issue

**Comment by ImaBlank2** [comment]
Alright, after a day of thinking with my little knowledge of python and tinkering, i was able to make it finally work not only in local but also in colab as well by just simply using the subprocess to call the EdgeGPT function in another python file, since it doesn't work if it's in the main script, i figured that it would be simple to just call the function in another file, i also merged kwisss's version of EdgeGPT which used GoogleWordcloud instead of Bing to let it act as an anti censorship, in case bing doesn't want to respond after getting asked by some NSFW or unethical questions by the user.

Heres the zip file: https://drive.google.com/file/d/1X6J9kuGnCXL8Me-voQWLWNwfdZz1RI1t/view?usp=drivesdk

**Comment by GiusTex** [comment]
Well done 👍🏻, I'm testing it. 
- I don't know though if I can include it in the repository since it uses pieces of kwisss's fork. Alternatively I was thinking of a colab SFW variant, which uses your own search_bot external to the script, with EdgeGPT instead of GoogleWordcloud, and if one doesn't want Bing censorship I can send him to your comment, so I don't directly include parts of kwisss' work; I hope there is no problem using redirection.
- So would it be okay for you if I changed your files like I described and included them in the repository, I would then add the link to your comment with the uncensored version, or would you prefer I don't add your edited work at all?
