### ISSUE TITLE
Cookie files no longer required

### ISSUE THREAD

**Issue by Malrama** [GiusTex/EdgeGPT#11]
As of version 0.5.0, EdgeGPT does no longer require cookie files. I think this extension needs an adaption to that.

Thank you very much and I really appreciate this extension!

**Comment by GiusTex** [comment]
I'll work on it in these days 👍🏻, thanks for the info

**Comment by Malrama** [comment]
Hey!

It does work, thank you. However, enabling this extension 
![Screenshot](https://github.com/GiusTex/EdgeGPT/assets/1287086/73a941d3-f252-426e-aedb-bc126111158f)
now changes the formatting of the output lines and adds a ":" to the beginning of each line. 

Maybe you could have a look at it? ^^ Otherwise it's working great. Thank you

**Comment by GiusTex** [comment]
I haven't looked yet sorry; also because I have some problems with the webui (never seen anything like this)

![image](https://github.com/GiusTex/EdgeGPT/assets/112352961/fe62c459-aa50-4a25-a082-3c19d950ee21)

and when I use EdgeGPT i get new errors (I think it's related to the red strange error), so for now I was postponing the problem..

**Comment by Malrama** [comment]
I was able to fix the issue by changing line 124 and 125 by replacing

`        '<|user|>': state['name1'].strip(),
        '<|bot|>': state['name2'].strip(),`
to

`        '<|user|>:': state['name1'].strip(),
        '<|bot|>:': state['name2'].strip(),`

I am using the instruct mode (most of the time).

**Comment by GiusTex** [comment]
My webui must be cursed cause if I use instruct mode with and without EdgeGPT I get `list index out of range`, and in normal chat sometimes I don't have the ":" error, sometimes I get it and sometimes EdgeGPT get stopped by the red error above, so I can't test it for now. Anyway, thanks for the info! When I have time and a working webui I'll continue the tests
