### ISSUE TITLE
EdgeGPT trashed my oobabooga install

### ISSUE THREAD

**Issue by Webslug** [GiusTex/EdgeGPT#17]
Before I installed this plugin my oobabooga was working perfectly fine.  

I couldn't get EdgeGPT to work so I deleted EdgeGPT and tried to run oobabooga again.  For some reason now oobabooga fake loads a model and it cannot start the Web UI.

In conclusion, I have learned not to install EdgeGPT again.  Hope this saves someone a future headache.

![image](https://github.com/GiusTex/EdgeGPT/assets/7551638/3de8ee0d-0bed-4220-b03a-94f20ddfb562)

**Comment by Webslug** [comment]
Clean installs work but Oogoobogga will no longer work with any model what so ever.  Despite a clean install.

I can only conclude this install some nasty Python plugin which is causing my issue.  

This is a nasty plugin, one which has caused hours of stress.

**Comment by GiusTex** [comment]
Strange.
- Are you using the last version of ooba?
- Are you using the last version of EdgeGpt? I don't see the printed EdgeGpt version (added in the last extension update)

**Comment by Webslug** [comment]
Yes, I just downloaded the latest version of Ooba and I reinstalled it.  Yes I did append it to a list.

My only goal now is to work out what damage EdgeGPT has done.  My fresh Oobaa install will not load any models now.

I knew I should of not have experimented when everything was working fine.

In a nutshell I am now in a worse situation than when I started.  It looks like I've lost my capability to use oobabooga unless I reformat which is a huge buzz kill.

**Comment by GiusTex** [comment]
Again, I don't think it's an extension error, they didn't even load (when they load you see `Loading [extension name]...ok/failed)`, and the console log in the photo didn't reach that point.
- From what I understand you haven't updated EdgeGpt, but it isn't the main problem now, since it isn't loaded.
- Try removing `EdgeGpt` from the extensions in `webui.py`. And if you want to remove the python script too you can run `windows_cmd.bat` and type `pip uninstall EdgeGPT`

**Comment by Webslug** [comment]
Thanks for trying to help - I won't ever use EdgeGPT again after this mornings fiasco with it.

The clean install refuses to load any of my existing models. 

oobabooga was the only thing bringing me joy lately.  I'm just sad that I've lost access to it now.

**The Morale of the story is, if it's not broken don't fix it.**
