### ISSUE TITLE
Option pannel not showing up

### ISSUE THREAD

**Issue by TheWhiteWord** [GiusTex/EdgeGPT#30]
### Describe the bug

Hi there,
I don't seem to find a way to load  EdgeGTP  in my Web UI interface. Can you tell me if there is something I am missing? 

Here is a description of my actions so far:

-I have installed the extension as instructed in your documentation. Installation went fine and no errors were reported.
-I have also installed the requirements via pip in the correct env.
-I have now an option to activate EdgeGTP in the "Session" tab. 
-I have clicked on that option and have that option alone active and clicked  on "apply flags/extensions and restart".

When saving the setting to Yalm I have confirmation of EdgeGPT to be selected
 <|prompt|>
autoload_model: false
default_extensions:
- EdgeGPT

I am more than willing to share any code snippet or image if needed.
Thanks for your time
TheWW

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Installation as described in the documentation (no errors)
Installation Requirements.txt (no errors and file present in folder)
Start Web-UI (no errors)
Select EdgeGPT and reload to apply (no errors)

Edge GPT manu not present **BUG** or  **wrong set up?**

### Screenshot

![Screenshot 2023-09-08 112522](https://github.com/GiusTex/EdgeGPT/assets/140733007/2d58f3e6-913d-49b6-944a-8b27214340f8)
![Screenshot 2023-09-08 112949](https://github.com/GiusTex/EdgeGPT/assets/140733007/1e1bc3b0-28c6-4b02-82ad-69336ba5400f)

### Logs

```shell
2023-09-08 11:52:28 ERROR:Failed to load the extension "EdgeGPT".
Traceback (most recent call last):
  File "C:\Users\DCinz\Desktop\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\extensions.py", line 35, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Users\DCinz\Desktop\oobabooga_windows\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 8, in <module>
    from EdgeGPT.EdgeGPT import Chatbot, ConversationStyle
ModuleNotFoundError: No module named 'EdgeGPT'
```

### System Info

```shell
AMD cpu only
16 RAM
```

**Comment by GiusTex** [comment]
> Failed to load the extension "EdgeGPT"
> ModuleNotFoundError: No module named 'EdgeGPT'

Did you use `cmd_windows.bat` to install the dependencies ? (The Edgegpt python module). It says Edgegpt isn't installed

**Comment by GiusTex** [comment]
The normal cmd isn't inside the text-generation-webui folder with its dependencies, so if you install things with cmd it will install them somewhere else. Cmd_windows.bat is set up so everything happens inside the text-generation-webui folder with its dependencies

**Comment by TheWhiteWord** [comment]
Thanks you have been so nice to explain. I appreciate.

However I have to tell you that there may be a problem: Bing output is null.


![Screenshot 2023-09-08 124753](https://github.com/GiusTex/EdgeGPT/assets/140733007/5c4ddcba-3a73-421f-84be-86ae848cfc71)

due to this:
![Screenshot 2023-09-08 124817](https://github.com/GiusTex/EdgeGPT/assets/140733007/c4a32ba5-aa60-49ce-978d-e3e76c0ec28a)

**Comment by GiusTex** [comment]
You have to usee cookies

**Comment by GiusTex** [comment]
Tell me if it works. If there are still errors you can open again this issue

**Comment by TheWhiteWord** [comment]
I tried with the cookies and the error is gone.
However, even if the console shows no error now, still no Bing output, unfortunately.

![Screenshot 2023-09-08 131601](https://github.com/GiusTex/EdgeGPT/assets/140733007/fff8b25c-5316-4353-b667-376ab7a85127)

CONSOLE READS CLEAN THOU:
 Bing what is the current date hour and year in Italy?
Llama.generate: prefix-match hit

llama_print_timings:        load time =  4502.04 ms
llama_print_timings:      sample time =    10.00 ms /    64 runs   (    0.16 ms per token,  6397.44 tokens per second)
llama_print_timings: prompt eval time =  1210.66 ms /    20 tokens (   60.53 ms per token,    16.52 tokens per second)
llama_print_timings:        eval time = 16533.93 ms /    63 runs   (  262.44 ms per token,     3.81 tokens per second)
llama_print_timings:       total time = 17881.54 ms
Output generated in 18.35 seconds (3.43 tokens/s, 63 tokens, context 460, seed 2049493424)

**Comment by GiusTex** [comment]
> Bing: None
> The current date and time in Rome, Italy, is...

The output is there, under "Bing: None". Maybe I'll fix it another day (it looks like the output is shown in the console, but not above the message in the webui). You can turn off `show bing output`.
And yes, I'm from Italy.

**Comment by TheWhiteWord** [comment]
OK non ti rubo piu' tempo. Ho trovato il problema:
Non aveva salvato la mia parola chiave senza "Hey". L' avevo messa in come "Bing" ma e' tornata al default.
Ora funziona tutto alla grande.
Comunque favoloso lavoro con questa extention sai. Se mi passi da Verona ti offro una birra.
Ciao

**Comment by GiusTex** [comment]
I know english, you don't have to speak italian. Comunque grazie lo stesso :)
Ah sei di Verona quindi, grandioso !
>  L' avevo messa in come "Bing" ma e' tornata al default.

Si bisogna sempre impostare all'inizio di ogni sessione se usare la parola chiave o se sovrascriverla.
> Comunque favoloso lavoro con questa extention sai

Sono felice ti piaccia!
