### ISSUE TITLE
modules not found

### ISSUE THREAD

**Issue by sorrrl** [GiusTex/EdgeGPT#31]
### Describe the enhancement

Exception has occurred: ModuleNotFoundError
No module named 'modules.shared'; 'modules' is not a package
AttributeError: module 'modules' has no attribute '__path__'

During handling of the above exception, another exception occurred:

  File "C:\Users\User\Desktop\EdgeGPT\script.py", line 5, in <module>
    import modules.shared as shared
ModuleNotFoundError: No module named 'modules.shared'; 'modules' is not a package

**Comment by GiusTex** [comment]
Can you answer the questions? You can find them in new issues (you can start one and not saving it, just to see the questions' text).
![image](https://github.com/GiusTex/EdgeGPT/assets/112352961/60c01b10-3505-40b8-87bf-fff22206c013)
![image](https://github.com/GiusTex/EdgeGPT/assets/112352961/a8b40a19-107d-4a23-8664-0e52a8063e3f)
![image](https://github.com/GiusTex/EdgeGPT/assets/112352961/172fe316-abfc-4c5d-af7d-9de7af2dbca7)

**Comment by leviuswafula** [comment]
check for possible errors mr.python

**Comment by GiusTex** [comment]
> check for possible errors

I found some (`No module named 'modules.shared'`), I just wanted more info if possible, before starting searching the problem

**Comment by sorrrl** [comment]
> > check for possible errors
> 
> I found some (`No module named 'modules.shared'`), I just wanted more info if possible, before starting searching the problem

root@WIN-DRPAT2EGLO4:~/bot/EdgeGPT# python script.py 
Traceback (most recent call last):
  File "/root/bot/EdgeGPT/script.py", line 5, in <module>
    import modules.shared as shared
ModuleNotFoundError: No module named 'modules'
