### ISSUE TITLE
It never searches

### ISSUE THREAD

**Issue by Takodachi6969** [GiusTex/EdgeGPT#4]
As the title says, everything was configured without any warnings. Except the bot never search anything and the Bing output will always be None

**Comment by GiusTex** [comment]
Can you use Bing bot on bing.com, the official site, if yes have you copied the edge cookies? If yes again you can try turning on "Overwrite activation word", this will make Bing search without needing a keyword; if this doesn't work tell me

**Comment by GiusTex** [comment]
If you still have errors you can open again this issue, or a new one

**Comment by ImaBlank2** [comment]
Why it doesn't search when using google colab? I pretty much did everything and the result was: "Bing: None" why is that?

**Comment by GiusTex** [comment]
Do you have a similar issue on colab? I read this email notification: "It never searches (Issue #4). Why it doesn't search when using google colab? I pretty much did everything and the result was: "Bing: None" why is that?" but I can't find your message here
